/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CenterView: typeof import('./../components/smart-cable/home-overview/centerView.vue')['default']
    Chart: typeof import('./../components/Chart/index.vue')['default']
    Detail1: typeof import('./../components/smart-cable/detail1.vue')['default']
    Detail2: typeof import('./../components/smart-cable/detail2.vue')['default']
    DetailCard: typeof import('./../components/smart-cable/home-overview/DetailCard.vue')['default']
    EchartMap: typeof import('./../components/smart-cable/dev-overview/EchartMap.vue')['default']
    FloatingBall: typeof import('./../components/smart-cable/floatingBall.vue')['default']
    GhostButton: typeof import('./../components/GhostButton.vue')['default']
    HomeOverview: typeof import('./../components/smart-cable/home-overview/index.vue')['default']
    Map: typeof import('./../components/smart-cable/dev-overview/map.vue')['default']
    NavBar: typeof import('./../components/NavBar.vue')['default']
    PieChartCard: typeof import('./../components/smart-cable/home-overview/PieChartCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./../components/TabBar.vue')['default']
    TransformerSubstationIcon: typeof import('./../components/icon/transformerSubstationIcon.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDialog: typeof import('vant/es')['Dialog']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopover: typeof import('vant/es')['Popover']
    VanSpace: typeof import('vant/es')['Space']
    VanStepper: typeof import('vant/es')['Stepper']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTreeSelect: typeof import('vant/es')['TreeSelect']
    VideoFrame: typeof import('./../components/smart-cable/videoFrame.vue')['default']
  }
}
