/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'charts': RouteRecordInfo<'charts', '/charts', Record<never, never>, Record<never, never>>,
    'counter': RouteRecordInfo<'counter', '/counter', Record<never, never>, Record<never, never>>,
    'devTools': RouteRecordInfo<'devTools', '/dev-tools', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'KeepAlive': RouteRecordInfo<'KeepAlive', '/keepalive', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'mock': RouteRecordInfo<'mock', '/mock', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
    'smartCable': RouteRecordInfo<'smartCable', '/smartCable', Record<never, never>, Record<never, never>>,
    'cableAlarm': RouteRecordInfo<'cableAlarm', '/smartCable/cable-alarm', Record<never, never>, Record<never, never>>,
    'devOverview': RouteRecordInfo<'devOverview', '/smartCable/dev-overview', Record<never, never>, Record<never, never>>,
    'deviceOverview': RouteRecordInfo<'deviceOverview', '/smartCable/dev-overview/deviceOverview', Record<never, never>, Record<never, never>>,
    'videoSurveillance': RouteRecordInfo<'videoSurveillance', '/smartCable/video-surveillance', Record<never, never>, Record<never, never>>,
    '/smartCable/video-surveillance/treeSelect': RouteRecordInfo<'/smartCable/video-surveillance/treeSelect', '/smartCable/video-surveillance/treeSelect', Record<never, never>, Record<never, never>>,
    '/smartCable/video-surveillance/videoSurveillance': RouteRecordInfo<'/smartCable/video-surveillance/videoSurveillance', '/smartCable/video-surveillance/videoSurveillance', Record<never, never>, Record<never, never>>,
  }
}
